
version: '2'
services:
  dewee-backend:
    image: move/dewee-backend
    ports:
      - "8099:8080"
      - "1883:1883"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - VIRTUAL_HOST=www.dewee.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8099
      - LETSENCRYPT_HOST=www.dewee.org
      - LETSENCRYPT_EMAIL=eedgaar@hotmail.com

  mongo:
    image: mongo

networks:
  default:
    external:
      name: nginx-proxy
